apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.10-3-jdk11
      imagePullPolicy: IfNotPresent
      tty: true
    - name: tools
      image: ghcr.io/eve-online-tools/jenkins-tools:0.2
      imagePullPolicy: IfNotPresent
      command:
        - cat
      tty: true
    - name: dind
      image: ghcr.io/eve-online-tools/dind-buildx:0.3
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      tty: true
      readinessProbe:
        exec:
          command: ["docker", "info"]
        initialDelaySeconds: 10
        failureThreshold: 6
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /root/.docker/config.json
          subPath: config.json
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: externalregistry
              items:
                - key: .dockerconfigjson
                  path: config.json
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/arch: amd64
  imagePullSecrets:
    - name: externalregistry